name: Stats Build

# on:   #se ejecuta con cada push
#   push:
#     branches: [main]

# on: #se ejecuta a las 12 de la noche
#   schedule:
#     - cron: '0 0 * * *'

jobs:     
  build: 
    if: gitgithub.repository == 'Prueba_Reflex'
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:  
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13.2' 
            
      - name: Run build script
        run: |
          # (chmod +x) para hacer el archivo ejecutable 
          chmod +x ./Python_link_bio/build_remoto.ps1   
        
          # el segundo (./Python_link_bio/build_remoto.ps1) para ejecutarlo
          ./Python_link_bio/build_remoto.ps1

      - name: Pull changes to ensure up-to-date with remote
        run: git pull origin main --rebase  # Esto sincroniza tu rama local con la remota
       
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Update stats build
          commit_user_name: Aldo Minoldo [Github-Actions]
          commit_user_email: minoldoaldo@gmail.com
          commit_author: "Aldo Minoldo <minoldoaldo@gmail.com>"  # Corregido aquí
